### ISSUE TITLE
[infra] Remove firebase config 

### ISSUE THREAD

**Issue by emperorgurgeh** [emperorgurgeh/desolates-map#11]
We're now using vercel for hosting

**Comment by jarvisjohnson** [comment]
looks like this is done yeah? 

https://github.com/emperorgurgeh/desolates-map/commit/b8d4fb93325118faae4d080208ad94ca6f94a555

still reference in the gitignore, but no biggie there

**Comment by emperorgurgeh** [comment]
Good catch, thanks. Closing
